### ISSUE TITLE
Reverb not recording traffic in Omniture

### ISSUE THREAD

**Issue by kdaledp** [denverpost/dpo-blogs-server#4]
When I go to site sections and open Reverb in Omniture, there is no traffic recorded since April 3 - the launch date of the new site. Must be fixed ASAP (or at least tell us where to find the data). Thanks!

**Comment by freejoe76** [comment]
Is Reverb a separate publication in Omniture? I don't see it on the accounts available to the denverpost user in omniture.

**Comment by freejoe76** [comment]
It's recording clicks somewhere. This is the data being sent to Omniture from http://www.heyreverb.com/blog/category/coats/

```
---------------- IMAGE REQUEST ----------------#1
http://mngi.112.2o7.net/b/ss/mngireverb/1/H.25/s73052394338883?AQB=1
ndh=1
t=10/3/2015 17:51:25 5 240
ce=UTF-8
pagename=Coats
url=http://www.heyreverb.com/blog/category/coats/
cc=USD
channel=Coats
events=event1
prop1=D=g
prop2=D=ch+"/?"
prop3=D=ch+"/?/?"
prop4=D=ch+"/?/?/?"
evar4=D=pageName
prop5=D=ch+"/?/?/?/?"
prop6=Coats
evar18=Browser
evar24=D=c43
prop33=D=c40+" / "+c50+" / "+c9
prop34=D=c40+" / "+c43+" / "+c50
prop35=D=v18+" / "+c40+" / "+c50
prop39=google.com / http%3a%2f%2fwww.heyreverb.com%2fblog%2fcategory%2fphotos%2fphoto-essay%2f / Coats
prop40=mngireverb
prop41=google.com / Coats
prop43=Coats
prop44=D=c40+" / "+c43+" / "+v26
prop45=D=c40+" / "+c43+" / "+c12
```

**Comment by kdaledp** [comment]
it hasn't been separate. I was wondering if we made it separate on this
launch, but i'm not seeing it in my list of products.

_KEVIN DALE_

News Director

(O) 303-954-1213 (F) 303-954-1090 // kdale@denverpost.com // _@kevindale
http://twitter.com/kevindale_ // Skype: kdale61

 The Denver Post

101 W. Colfax Ave. // Denver CO 80202

 Colorado's breaking news, photos, weather, sports and traffic:
www.denverpost.com

**Comment by freejoe76** [comment]
Okay, yea, I see what you're talking about.

I put a fix in, but I can't push that fix live without @schneidan's bitbucket password, so when Dan gets back we'll get that live.

**Comment by schneidan** [comment]
Man, sorry about that, guys. 

I've pushed Joe's fix live, so let's start looking for traffic in Omniture.

Joe, any reason this couldn't be a public /denverpost repo going forward? I used BitBucket+private just to keep it kinda secret until launch, but it's launched now. If I move it over there, we won't need to worry about passwords anymore. thoughts?

**Comment by freejoe76** [comment]
Re: repo location, sure, I'll chat with you about that.
