### ISSUE TITLE
Olympics blog isn't showing up in the blogs rotator

### ISSUE THREAD

**Issue by danielboniface** [denverpost/dpo-blogs-server#5]
http://blogs.denverpost.com/olympics

cc. @schneidan

**Comment by freejoe76** [comment]
I added the Olympics blog to the homepage rotator.

**Comment by schneidan** [comment]
Oh cool. Thanks, Joe!

Daniel J. Schneider
Photographer and Journalist
Denver, Coloradohttp://www.scrollwright.com

twitter.com/schneidan

720.732.1763

**Comment by danielboniface** [comment]
Awesome thanks @freejoe76 and @schneidan

**Comment by thejoenguyen** [comment]
Hey @freejoe76, would you mind adding it to the sports rotator, too? Looks like it's not showing up there.

**Comment by freejoe76** [comment]
Sure @thejoenguyen, this is done.
