### ISSUE TITLE
Need ads on the mobile blogs theme

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dpo-blogs-server#6]
Hi @schneidan @freejoe76 -- We have no ads on the mobile view of our blogs theme. Would it be possible to get a 300 x 250 ad below the byline, and before the content starts, and then one at the end of the content? Thanks much, Dan

**Comment by freejoe76** [comment]
Example URL http://blogs.denverpost.com/ridetherockies/2015/06/20/westcliffe-colorado-ride-the-rockies-2015-day-7/3232/

**Comment by freejoe76** [comment]
Okay, I added three ad positions specific to mobile. One after the byline, one before the comments, one in the footer. There aren't any js errors, however, no ads are displaying. Cube ads not displaying on blogs isn't unusual in desktop, so I'll consider this issue closed.

**Comment by freejoe76** [comment]
I'm seeing ads on mobile now.

**Comment by schneidan** [comment]
The cube ad in the right rail should still display , but they don't seem to have inventory all the time, especially depending on the blog.

Daniel J. Schneider
Photographer and Journalist
Denver, Coloradohttp://www.scrollwright.com

twitter.com/schneidan

720.732.1763

**Comment by danielpetty** [comment]
@schneidan: Looking to see if we can guarantee 300 x 250 (I saw smushed skyscraper ad) and center the ad on the screen, add the phrase "advertisement" to the top and put a light gray border around the box itself. Example story with ads displaying:

http://blogs.denverpost.com/ostrow/2015/12/07/kunc-to-buy-second-station-split-musicnews-formats/23725/

**Comment by schneidan** [comment]
Done.
