### ISSUE TITLE
Change Twitter preview image to be "large" so it appears as such on mobile Twitter

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dpo-blogs-server#7]
Here's an example, with this story: http://dpo.st/1OVVU2h

As it appears on Twitter: https://twitter.com/danielpetty/status/682089260028047360

The image is only square, rather than a rectangle that stretches the width of a detailed tweet.

**Comment by schneidan** [comment]
It already is. The markup on that page is:

`<meta name="twitter:image" value="http://blogs.denverpost.com/broncos/files/2015/12/brock-osweiler1-495x329.jpg" />`

**Comment by danielpetty** [comment]
I should have clarified more. We need to switch this meta tag from:

`<meta name="twitter:card" content="summary" />`

To this:

`<meta name="twitter:card" content="summary_large_image" />`

**Comment by schneidan** [comment]
Gotcha. Made this fix.
