### ISSUE TITLE
Add Author stats in blogs Google Analytics

### ISSUE THREAD

**Issue by rebeccarisch** [denverpost/dpo-blogs-server#8]
Would like to get GA tracking Author pageviews on the DP blogs.

Is this something you could add without having to go through DFM?

**Comment by freejoe76** [comment]
Hi Becky can you give me a URL of a page that you'd like to see tracked?

**Comment by rebeccarisch** [comment]
Joe, I forget where this stands.

**Comment by freejoe76** [comment]
@rebeccarisch I forgot to forward you DFM's update from last week: "Just a heas up we're still working on this , but we're blocked until we get approval of our new Qa and approval process. "

**Comment by rebeccarisch** [comment]
Ok, thanks

**Comment by freejoe76** [comment]
Oh wait, I did forward you that update when they sent it. Ha!

**Comment by freejoe76** [comment]
This is done.
